### ISSUE TITLE
optie om meerdere processen aan te maken

### ISSUE THREAD

**Issue by mprins** [B3Partners/CVnHR-Open-Source#22]
Er kan nu maar 1 batch proces geconfigureerd worden, als je voor een waterschap alle postcodes periodiek op wilt halen wordt dat een nogal onoverzichtelijk geheel. Het zou mooi zijn ale er meerdere batch process zouden zijn.

**Comment by mprins** [comment]
@mvdstruijk dit zit er toch in met #32?

**Comment by CorneHogerheijde** [comment]
@mprins @mvdstruijk 
Volgens mij zit dit er ook al in met #32 => Ik gebruik deze nog om wat kleine tweaks in gebruik hiervoor mee te nemen, komt een PR hierover aan.
