### ISSUE TITLE
Stoppen met transformeren van geselecteerde 'STAGING_OK' berichten door BrmoSyncService.cs na aanbieden

### ISSUE THREAD

**Issue by mprins** [B3Partners/CVnHR-Open-Source#26]
Het transformeren van berichten is een taak van de brmo-service, of een beheerder via de gebruikersinterface.

Op dit moment gebruikt de CVnHR een reverse-engineered url om STAGING_OK berichten te selecteren in de gui van de brmo-service en vervolgens die berichten te transformeren, dat is foutgevoelig / veroorzaakt fouten.

Wat er gebeurt is dat er -tijdens bulk update, bijv. 4-pos. postcode gebieden- geselecteerde berichten in meerdere pipelines terecht lijken te komen omdat de status pas na afloop van transformeren wordt ingesteld, daardoor ontstaan problemen als in B3Partners/brmo#512 waar in de brmo-service voor een insert wordt gekozen omdat een key niet bestaat, maar in de commit die key er wel is en er een 

De werking van transformatie is ongeveer de volgende:
1. selecteren STAGING_OK berichten
2. kopiëren van STAGING_OK berichten naar job tabel, zonder status info
3. in blokken van 1000 berichten uit de job tabel transformeren
4. na transformeren van een bericht de status bijwerken in de bericht tabel
5. records van het bericht uit de job tabel verwijderen

CVnHR zou na afloop van verwerken van een batch hooguit 1 call (`Transform.action?transformAll`) moeten doen om (alle) STAGING_OK berichten te transformeren, maar liever eigenlijk ook niet; beter is om dat via een automatisch proces in te regelen

zie ook: B3Partners/brmo#512

**Comment by mprins** [comment]
https://github.com/B3Partners/CVnHR-Open-Source/blob/79a1f313215f6775f6e29b8c37da546f0c547dc3/QNH.Overheid.KernRegister.Business/Service/BRMO/BrmoSyncService.cs#L33-L35

https://github.com/B3Partners/CVnHR-Open-Source/blob/79a1f313215f6775f6e29b8c37da546f0c547dc3/QNH.Overheid.KernRegister.Business/Service/BRMO/BrmoSyncService.cs#L109-L110

**Comment by CorneHogerheijde** [comment]
Hoi Mark, 

Lijkt me goed punt. Ik zie dat je jezelf als assignee hebt gezet, maar ik zou hem nu/vandaag ook op kunnen pakken?

Groet!
